[colors]
background = '#eff1f5'
foreground = '#4c4f69'
selection-background = '#dce0e8'
selection-foreground = '#4c4f69'
cursor = '#6c7086'
black = '#4c4f69'
red = '#d20f39'
green = '#40a02b'
yellow = '#df8e1d'
blue = '#1e66f5'
magenta = '#ea76cb'
cyan = '#179299'
white = '#acb0be'
light_black = '#6c7086'
light_red = '#e64553'
light_green = '#4da849'
light_yellow = '#ef9f2a'
light_blue = '#3c7bf5'
light_magenta = '#ec92d3'
light_cyan = '#26a3a6'
light_white = '#bcc0cc'
